### ISSUE TITLE
downloadImage 函数填参数似乎也没有用

### ISSUE THREAD

**Issue by TheBadZhang** [only52607/lua-mirai#10]
不知道如果不依赖 toTable 应该如何下载所有图片？（可能吗？）

**Comment by only52607** [comment]
不能，如果直接对msg对象使用downloadImage，会默认下载msg中的第一张图片。

**Comment by TheBadZhang** [comment]
> 不能，如果直接对msg对象使用downloadImage，会默认下载msg中的第一张图片。

标题标题，downloadImage 参数不能指定文件名

**Comment by only52607** [comment]
报什么错呢

**Comment by TheBadZhang** [comment]
> 报什么错呢

无报错，直接保存为以msg为文件名的文件

**Comment by only52607** [comment]
已找到问题，下个版本修复。
