### ISSUE TITLE
subscribeMemberJoinEvent的响应问题

### ISSUE THREAD

**Issue by Miaow233** [only52607/lua-mirai#15]
`subscribeMemberJoinEvent`这个订阅事件不会自动销毁吗?  这是脚本重载三次的结果
<img src="https://user-images.githubusercontent.com/57578021/89004895-c4667d80-d335-11ea-9653-3d6ee1bea681.png" width=45%></img><img src="https://user-images.githubusercontent.com/57578021/89005368-dbf23600-d336-11ea-874a-5a77cf735d22.png" width=55%></img>
也就是说同一事件会触发多次
貌似只有这一个会这样

**Comment by TheBadZhang** [comment]
啊这？文档不是告诉你return true截断事件么

**Comment by Miaow233** [comment]
Mirai安卓端暂时停止了，这个bug也不会复现了(笑)
