### ISSUE TITLE
哇，这怎么用啊，是 console 的插件还是一个独立的程序啊？

### ISSUE THREAD

**Issue by TheBadZhang** [only52607/lua-mirai#2]
如果是插件的话，并不能插啊，

如果是一个独立的程序，什么参数可以运行啊

编译我也搞不来啊，从来没接触过 java，用的都是 c++ 那一套，java 真的不懂啊 QAQ

**Comment by sam01101** [comment]
小白。。。这里建议去用Java
Lua的语法简单，但通常情况请使用Java来进行开发

**Comment by TheBadZhang** [comment]
> 小白。。。这里建议去用Java
> Lua的语法简单，但通常情况请使用Java来进行开发

不是……java -jar lua-mirai-xxx.jar 运行之后报错……我现在用的 mirai-android 里面的 lua-mirai 勉强度度日子（单纯没有很大的动力去学习java罢了

**Comment by TheBadZhang** [comment]
<img width="646" alt="Snipaste_2020-07-03_00-35-03" src="https://user-images.githubusercontent.com/21277507/86387014-21363000-bcc5-11ea-972d-712fd0f1a1ee.png">
这是运行结果

**Comment by only52607** [comment]
> <img alt="Snipaste_2020-07-03_00-35-03" width="646" src="https://user-images.githubusercontent.com/21277507/86387014-21363000-bcc5-11ea-972d-712fd0f1a1ee.png">
> 
> 这是运行结果

命令格式应该是这样的 
java -jar lua-mirai.jar 脚本路径

例如:
java -jar lua-mirai.jar C:\xxx.lua

**Comment by TheBadZhang** [comment]
> > <img alt="Snipaste_2020-07-03_00-35-03" width="646" src="https://user-images.githubusercontent.com/21277507/86387014-21363000-bcc5-11ea-972d-712fd0f1a1ee.png">
> > 这是运行结果
> 
> 命令格式应该是这样的
> java -jar lua-mirai.jar 脚本路径
> 
> 例如:
> java -jar lua-mirai.jar C:\xxx.lua

<img width="606" alt="Snipaste_2020-07-10_21-41-12" src="https://user-images.githubusercontent.com/21277507/87160820-282cf600-c2f6-11ea-97bb-fe70372aa863.png">


可是lua代码要怎么写呢？我写了一份可以放在 mirai-android 里面跑的，复制到服务器上又不能跑了，用了项目中提供的彩虹屁demo也不能跑，
