### ISSUE TITLE
几种对象中的属性中 bot 和 group 指的是什么？应该如何使用

### ISSUE THREAD

**Issue by TheBadZhang** [only52607/lua-mirai#3]

**Comment by sam01101** [comment]
以你目前的问题来说

bot：机器人本身（你登录的机器人账号自己）
group：群组

如果需要更清晰的答案请把你的问题描述得更好

在 2020年6月25日週四 下午3:56，贱人张 <notifications@github.com> 寫道：

**Comment by TheBadZhang** [comment]
> 以你目前的问题来说 bot：机器人本身（你登录的机器人账号自己） group：群组 如果需要更清晰的答案请把你的问题描述得更好

我不是很明白，既然我可以直接把 bot 和 group 作为参数传到函数内部，为什么我还需要这种脱裤子放屁的方式

**Comment by only52607** [comment]
> > 以你目前的问题来说 bot：机器人本身（你登录的机器人账号自己） group：群组 如果需要更清晰的答案请把你的问题描述得更好
> 
> 我不是很明白，既然我可以直接把 bot 和 group 作为参数传到函数内部，为什么我还需要这种脱裤子放屁的方式
是的，你也可以通过这种方式获得bot和group对象，但是当我没有保存bot对象的时候，也可以通过friend或者group对象获得bot对象。
