### ISSUE TITLE
ImageUrl函数无法构建消息对象

### ISSUE THREAD

**Issue by NeptuneQ** [only52607/lua-mirai#31]
我尝试使用ImageUrl函数来构建消息, 但调用函数后, 出现'Can't find match method "sendMessage"'的错误

图片链接: https://i.imgur.com/0Ohxqw9.png

这是源码
![image](https://user-images.githubusercontent.com/36855785/92293884-70b10a80-ef59-11ea-8be7-48828f739b6c.png)

这是错误发生时的截图
![image](https://user-images.githubusercontent.com/36855785/92296480-bc6ab080-ef67-11ea-8b5c-845ece5c56c4.png)
![image](https://user-images.githubusercontent.com/36855785/92293912-9c33f500-ef59-11ea-8d54-1f300075cd30.png)

**Comment by only52607** [comment]
> 我尝试使用ImageUrl函数来构建消息, 但调用函数后, 出现'Can't find match method "sendMessage"'的错误
> 
> 图片链接: https://i.imgur.com/0Ohxqw9.png
> 
> 这是源码
> ![image](https://user-images.githubusercontent.com/36855785/92293884-70b10a80-ef59-11ea-8be7-48828f739b6c.png)
> 
> 这是错误发生时的截图
> ![image](https://user-images.githubusercontent.com/36855785/92296480-bc6ab080-ef67-11ea-8b5c-845ece5c56c4.png)
> ![image](https://user-images.githubusercontent.com/36855785/92293912-9c33f500-ef59-11ea-8d54-1f300075cd30.png)

你用的版本是多少？

**Comment by NeptuneQ** [comment]
> > 我尝试使用ImageUrl函数来构建消息, 但调用函数后, 出现'Can't find match method "sendMessage"'的错误
> > 图片链接: https://i.imgur.com/0Ohxqw9.png
> > 这是源码
> > ![image](https://user-images.githubusercontent.com/36855785/92293884-70b10a80-ef59-11ea-8be7-48828f739b6c.png)
> > 这是错误发生时的截图
> > ![image](https://user-images.githubusercontent.com/36855785/92296480-bc6ab080-ef67-11ea-8b5c-845ece5c56c4.png)
> > ![image](https://user-images.githubusercontent.com/36855785/92293912-9c33f500-ef59-11ea-8d54-1f300075cd30.png)
> 
> 你用的版本是多少？

最新的编译版本
