### ISSUE TITLE
Json转table的问题

### ISSUE THREAD

**Issue by kjundada** [only52607/lua-mirai#42]
我所写的代码
```
bot:subscribe(
	"GroupMessageEvent",function(event)        
		if event.message:find("/pii")  then
			pii_jtt = {}
			pii_value1 = event.message:gsub("/pii","")
			pii_value = pii_value1:gsub(" ","")
			pii_json = ("https://kspixivapi.herokuapp.com/v1/illust/detail/" .. pii_value)
			pii_get_json = Http.get(pii_json)
			pii_jtt = Json.parseJson(pii_get_json)
			pii_title = pii_jtt["title"]
      		pii_painter = pii_jtt["user"]["name"]
			pii_id = pii_jtt["id"]
			--pii_create_date = pii_jtt["create_date"]
			pii_o_pic = pii_jtt["meta_single_page"]["original_image_url"]
			pii_pic = pii_o_pic:gsub("i.pximg.net","i.pixiv.cat")
      		--pii_pic = ([["]] .. pii_pic_1 .. [["]])
			event.group:sendMessage( ImageUrl(pii_pic,group) .. "名称：" .. pii_title .. "," .. "画师名称:" .. pii_painter .. "," .. "图画ID:" .. pii_id) --这行报错
    end
  end)
```
但是会报错，错误log如下：
```
2020-10-22 20:42:25 E/Bot 1654723334: An exception was thrown under a coroutine of Bot
org.luaj.vm2.LuaError: @aio.lua:133 vm error: java.lang.Exception: Could not convert LuaValue to Any!
```

**Comment by only52607** [comment]
> 我所写的代码
> 
> ```
> bot:subscribe(
> 	"GroupMessageEvent",function(event)        
> 		if event.message:find("/pii")  then
> 			pii_jtt = {}
> 			pii_value1 = event.message:gsub("/pii","")
> 			pii_value = pii_value1:gsub(" ","")
> 			pii_json = ("https://kspixivapi.herokuapp.com/v1/illust/detail/" .. pii_value)
> 			pii_get_json = Http.get(pii_json)
> 			pii_jtt = Json.parseJson(pii_get_json)
> 			pii_title = pii_jtt["title"]
>       		pii_painter = pii_jtt["user"]["name"]
> 			pii_id = pii_jtt["id"]
> 			--pii_create_date = pii_jtt["create_date"]
> 			pii_o_pic = pii_jtt["meta_single_page"]["original_image_url"]
> 			pii_pic = pii_o_pic:gsub("i.pximg.net","i.pixiv.cat")
>       		--pii_pic = ([["]] .. pii_pic_1 .. [["]])
> 			event.group:sendMessage( ImageUrl(pii_pic,group) .. "名称：" .. pii_title .. "," .. "画师名称:" .. pii_painter .. "," .. "图画ID:" .. pii_id) --这行报错
>     end
>   end)
> ```
> 
> 但是会报错，错误log如下：
> 
> ```
> 2020-10-22 20:42:25 E/Bot 1654723334: An exception was thrown under a coroutine of Bot
> org.luaj.vm2.LuaError: @aio.lua:133 vm error: java.lang.Exception: Could not convert LuaValue to Any!
> ```

group是未知变量，改用event.group
