### ISSUE TITLE
获取及构造bot对象相关

### ISSUE THREAD

**Issue by Uwwal** [only52607/lua-mirai#52]
1 按照文档使用
![image](https://user-images.githubusercontent.com/69232066/107882744-2e3b2300-6f26-11eb-8e72-fbcb0546b019.png)
每次构造bot对象均需验证设备
2 考虑到登陆后本地未检索到device.json文件
分别尝试传入使用带有\\和/的绝对路径 如"D:\\\\material\\\\mirai\\\\device.json"
依旧![image](https://user-images.githubusercontent.com/69232066/107883001-3b0c4680-6f27-11eb-9922-abebaef3f223.png)
3 传入带有fileBasedDeviceInfo成员的table 依旧如此

* 同时注意到 登陆后未获取到群聊消息 onLoad(bot)会红字显示nil
* 尝试使用脚本创建文件 成功

4 尝试使用console登录 登录成功并获取到对应device.json
在脚本中构造bot对象依旧需要验证
5 尝试在脚本中遍历bot对象
![image](https://user-images.githubusercontent.com/69232066/107883140-149adb00-6f28-11eb-8011-7148f5cd3f12.png)
输出如下
![image](https://user-images.githubusercontent.com/69232066/107883168-4b70f100-6f28-11eb-9952-8d7015e67be7.png)

lua-mirai版本为2.0.2 
console和core版本为2.4

**Comment by only52607** [comment]
onLoad函数已移除
其他问题已修复：[https://github.com/only52607/lua-mirai/releases/tag/v2.0.9](v2.0.9)
