### ISSUE TITLE
希望从Console启动时自动加载config\lua-mirai\lua 文件夹下的所有lua脚本

### ISSUE THREAD

**Issue by IOL0ol1** [only52607/lua-mirai#57]

**Comment by only52607** [comment]
console版本已经有脚本载入记忆了，在console成功载入的脚本在第二次启动console时会自动载入。

**Comment by IOL0ol1** [comment]
> console版本已经有脚本载入记忆了，在console成功载入的脚本在第二次启动console时会自动载入。

json文件即使填了相对路径，也会自动改回绝对路径
