### ISSUE TITLE
没有在群内被at的事件

### ISSUE THREAD

**Issue by 1845598311** [only52607/lua-mirai#58]
既然有戳一戳的事件，我本以为是有被@的事件的，结果发现并没有
虽然可以用其他方法来替代，但是总归没有那么方面
后续有没有可能加上这个事件呢

**Comment by sam01101** [comment]
> 既然有戳一戳的事件，我本以为是有被@的事件的，结果发现并没有
> 虽然可以用其他方法来替代，但是总归没有那么方面
> 后续有没有可能加上这个事件呢

`[CQ:at,qq=10001]`
https://docs.go-cqhttp.org/cqcode/#%E6%9F%90%E4%BA%BA

**Comment by only52607** [comment]
> 既然有戳一戳的事件，我本以为是有被@的事件的，结果发现并没有
> 虽然可以用其他方法来替代，但是总归没有那么方面
> 后续有没有可能加上这个事件呢

以后大概率不会被加上，和戳一戳事件不同，严格来说它不属于一类单独的事件（与消息事件重复）。后续可能会通过改善消息检索的api的方式来改善体验。

**Comment by 1845598311** [comment]
> > 既然有戳一戳的事件，我本以为是有被@的事件的，结果发现并没有
> > 虽然可以用其他方法来替代，但是总归没有那么方面
> > 后续有没有可能加上这个事件呢
> 
> 以后大概率不会被加上，和戳一戳事件不同，严格来说它不属于一类单独的事件（与消息事件重复）。后续可能会通过改善消息检索的api的方式来改善体验。

thanks for your answer!
