### ISSUE TITLE
subscribeMemberJoinEvent 和 subscribeMemberInvitedEvent 传入的参数是否有些不太对的地方？

### ISSUE THREAD

**Issue by TheBadZhang** [only52607/lua-mirai#6]
照理来说，subscribeMemberInvitedEvent 应该还有个是谁邀请的（？）否则和 subscribeMemberJoinEvent 不是被包含的关系么？

**Comment by only52607** [comment]
谢谢提醒，subscribeMemberInvitedEvent事件应该是不存在的，下个会将它移除并改为subscribeMemberJoinRequestEvent，代表成员申请加群事件。
