### ISSUE TITLE
解析json的问题

### ISSUE THREAD

**Issue by 1845598311** [only52607/lua-mirai#60]
在使用中，我想解析一段json，我使用了文档中的json支持库中的函数，代码片段如下：
`        local a =232313
        local msg = Http.get("http://api.qingyunke.com/api.php?key=free&appid=0&msg=" ..a)
        local t = Json.parseJson(msg)
        local status = t["content"]
        group:sendMessgae(status)`
显示最后一行请求了nil，也尝试过将status给tostring但仍然出错，不知该如何结果

还有就是这里支持cjson嘛

**Comment by 1845598311** [comment]
`        local a =232313
        local msg = Http.get("http://api.qingyunke.com/api.php?key=free&appid=0&msg=" ..a)
        local t = Json.parseJson(msg)
        local status = t["content"]
        group:sendMessgae(status)
`

**Comment by 1845598311** [comment]
local a =232313
        local msg = Http.get("http://api.qingyunke.com/api.php?key=free&appid=0&msg=" ..a)
        local t = Json.parseJson(msg)
        local status = t["content"]
        group:sendMessgae(status)

**Comment by only52607** [comment]
> ```
>     local a =232313
>     local msg = Http.get("http://api.qingyunke.com/api.php?key=free&appid=0&msg=" ..a)
>     local t = Json.parseJson(msg)
>     local status = t["content"]
>     group:sendMessgae(status)
> ```

检查是否是拼写问题，sendMessgae -> sendMessage

**Comment by 1845598311** [comment]
草，谢谢，大意了
