### ISSUE TITLE
几个bug(也许是)

### ISSUE THREAD

**Issue by xxj7527** [only52607/lua-mirai#64]
嘿嘿我来啦!

bug：

> 1.quote里的originalMessage显示不全 不知道是mirai的问题还是luamirai

> 2.post无论怎么写都提示缺少body(https://github.com/only52607/LuaMiraiForAndroid/issues/4)

> 在(#74)中分离出  ~~3.chat-command中使用/lua相关命令报错(https://github.com/only52607/lua-mirai/issues/63)~~

> 4.别的插件触发httpapi时，会把指令消息重新监听，比如我用指令"开启复读机"新增一个Event监听，正常情况不会复读"开启复读机"而别的插件触发httpapi时，就算后续关闭插件，都会把指令复读，监听不精确。

> 5.无法发送图片。

todo：
> 1.无法查看IntArray数组，等后续支持转table

> 2.期待增加[ `MiraiCode.deserializeFromMiraiCode`]
(https://github.com/mamoe/mirai/blob/dev/docs/Messages.md#%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF)
`[EventChannel](https://github.com/mamoe/mirai/blob/dev/docs/Events.md#%E5%9C%A8-eventchannel-%E7%9B%91%E5%90%AC%E4%BA%8B%E4%BB%B6)`中的EventChannel.subscribeAlways 等api

> 3.异步api(线程放sleep无限循环无法停止)

> 在(#75)中解决  ~~4.建议加一个运行自动运行某个脚本源生成脚本的命令，这样重启就不用多次重复手动加载某些必备的插件。像java独立版那样自动加载ai.lua就不错 实现开机全自动~~

**Comment by only52607** [comment]
不同的问题请分开多个issue

**Comment by xxj7527** [comment]
> 不同的问题请分开多个issue

好的 初用github 排版略丑 正在改 没想到update也会通知 那我这样怪烦人的。。。

**Comment by xxj7527** [comment]
全部分开了，也不知道会不会一直通知作者，尽量都今天全分开，以后就不会烦了。update我也不知道会不会通知，close再回答我也不知道有没有通知，不过作者应该是从75被引用进来的，唉不管了，这个我关了。
