### ISSUE TITLE
emoji显示错误

### ISSUE THREAD

**Issue by jiangyuxian** [only52607/lua-mirai#79]
![Screenshot_20220519-215512](https://user-images.githubusercontent.com/92676720/169311450-5565ea24-71bb-4336-9497-8cb36d5c25c5.png)
错误的emoji为"💮"
发消息或者日志都这样,希望有空能修一下

**Comment by only52607** [comment]
请到[LuaMiraiForAndroid](https://github.com/only52607/LuaMiraiForAndroid/issues)处反馈
