### ISSUE TITLE
似乎没有办法同意好友请求？

### ISSUE THREAD

**Issue by Redbeanw44602** [only52607/lua-mirai#85]
事件 `NewFriendRequestEvent`

翻遍了文档，没有找到同意好友请求的办法（可能是我看漏了吗emm?

Mirai是可以同意的，如果没有这个接口的话，能否考虑添加一下？

**Comment by only52607** [comment]
文档可能写漏了，你按照mirai的api调用就可以，具体做法是调用该event的accept方法，即```
event.accept()
```。

**Comment by Redbeanw44602** [comment]
好，非常感谢。
